# Generated by Django 3.0.5 on 2020-06-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('mobile', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('emailid', models.EmailField(max_length=254)),
            ],
        ),
    ]
